# DO NOT EDIT THIS FILE !
# Instead update $HOME/.zshrc.local

# ZSH config
for file in $HOME/.config/zsh/*; do
  source "$file"
done

if [[ -f $HOME/.zshrc.local ]]; then
  source $HOME/.zshrc.local
fi

# Initialize starship
if type starship >/dev/null; then
  eval "$(starship init zsh)"
fi

# Initialize zoxide
if type zoxide >/dev/null; then
  eval "$(zoxide init zsh)"
fi
