"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format = """
 $sudo\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$line_break\
 [](fg:bright-black)\
[\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\
$character\
](bg: bright-black)[](bold black) """

right_format = """
$cmd_duration
"""

continuation_prompt = " [](bright-black) "

[directory]
style = "bold red"
truncation_length = 6
truncation_symbol = ".../"
format = ' [$path]($style)[$read_only]($read_only_style) '
repo_root_format = ' [git]($before_repo_root_style):[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
before_repo_root_style = 'cyan'
repo_root_style = 'bold red'
read_only = ''
home_symbol = ""

[sudo]
disabled = false
style = "bold cyan"
format = '\([$symbol]($style)\)'
symbol = "󰨒"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
deleted = "x"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
style = "white"

[cmd_duration]
disabled = false
format = '\([$duration]($style)\)'
min_time = 5000
style = "white"

[jobs]
format = '[$symbol$number ]($style)'
style = "bg:bright-black"

[character]
format = '$symbol'
error_symbol = ""
success_symbol = "[](bg:bright-black)"

# SYMBOLS
[status]
disabled = false
format = '[$symbol$status_common_meaning$status_signal_name$status_maybe_int]($style)'
map_symbol = true
pipestatus = true
symbol = ""
not_found_symbol = ""
sigint_symbol = ""
signal_symbol = "⚡"
style = "bold white bg:bright-black"

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "
style = "bold red"

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
