"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2000
format = """
 $sudo\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$cmd_duration\
$line_break\
 [](fg:bright-black)\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\
$character\
[](fg:bright-black) 
"""

continuation_prompt = " [](bright-black) "

[directory]
style = "purple"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "git: "
home_symbol = ""
read_only = ""

[sudo]
disabled = false
format = '[$symbol]($style) '
symbol = "󰨒"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
deleted = "x"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
style = "white"

[cmd_duration]
disabled = false
format = '\([$duration]($style)\)'
min_time = 1000
style = "white"

[character]
error_symbol = ""
success_symbol = ""
format = "[$symbol](fg:bright-white bg:bright-black)"


# SYMBOLS
[status]
disabled = false
format = '[$symbol]($style)'
style = "bold red bg:bright-black"
map_symbol = true
pipestatus = true
symbol = ""
not_executable_symbol = "󰂭"
not_found_symbol = ""
sigint_symbol = "⚡"
signal_symbol = "⚡"

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
